### PR TITLE
Work around broken WASM streaming in extensions

### PR DESCRIPTION
**Pull request by callahad**
See: https://bugzil.la/1470182

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks for the PR!  Unfortunately, this will break things when in the context of non-WebExtension Chromium (which requires the streaming API).  Is it possible to detect that we're in a WebExtension and only do this in that case?

**Comment by callahad** [comment]
@mdboom Wait... can you tell me more about Chromium requiring the streaming API? The non-streaming API is the initial API proposed by WASM, so it should be supported everywhere.

**Comment by mdboom** [comment]
Ah, I think I misremembered the issue.  The issue is that you can't compile WASM larger than 4k on the main thread in Chrome.  So you can't use the synchronous APIs, but it looks like this is still asynchronous, so might be ok.  I'll go check...

**Comment by mdboom** [comment]
Ah, I think I misremembered the issue.  The issue is that you can't compile WASM larger than 4k on the main thread in Chrome.  So you can't use the synchronous APIs, but it looks like this is still asynchronous, so might be ok.  I'll go check...

**Pull request merged**
